/*
 * Terminal colour schemes (TERM-9): built-in gallery, custom schemes from settings, and conversion to xterm's ITheme.
 * Colours are stored as #rrggbb (search decorations and the scheme editor require that format).
 */
import type { ITheme } from '@xterm/xterm'
import { ANSI_KEYS, type TerminalScheme } from './types'
import type { TerminalSettings } from './settings'

type S = Omit<TerminalScheme, 'id' | 'name'>

const TANGO: Pick<S, (typeof ANSI_KEYS)[number]> = {
  black: '#2e3436',
  red: '#cc0000',
  green: '#4e9a06',
  yellow: '#c4a000',
  blue: '#3465a4',
  magenta: '#75507b',
  cyan: '#06989a',
  white: '#d3d7cf',
  brightBlack: '#555753',
  brightRed: '#ef2929',
  brightGreen: '#8ae234',
  brightYellow: '#fce94f',
  brightBlue: '#729fcf',
  brightMagenta: '#ad7fa8',
  brightCyan: '#34e2e2',
  brightWhite: '#eeeeec',
}

const CAMPBELL: Pick<S, (typeof ANSI_KEYS)[number]> = {
  black: '#0c0c0c',
  red: '#c50f1f',
  green: '#13a10e',
  yellow: '#c19c00',
  blue: '#0037da',
  magenta: '#881798',
  cyan: '#3a96dd',
  white: '#cccccc',
  brightBlack: '#767676',
  brightRed: '#e74856',
  brightGreen: '#16c60c',
  brightYellow: '#f9f1a5',
  brightBlue: '#3b78ff',
  brightMagenta: '#b4009e',
  brightCyan: '#61d6d6',
  brightWhite: '#f2f2f2',
}

const SOLARIZED: Pick<S, (typeof ANSI_KEYS)[number]> = {
  black: '#073642',
  red: '#dc322f',
  green: '#859900',
  yellow: '#b58900',
  blue: '#268bd2',
  magenta: '#d33682',
  cyan: '#2aa198',
  white: '#eee8d5',
  brightBlack: '#002b36',
  brightRed: '#cb4b16',
  brightGreen: '#586e75',
  brightYellow: '#657b83',
  brightBlue: '#839496',
  brightMagenta: '#6c71c4',
  brightCyan: '#93a1a1',
  brightWhite: '#fdf6e3',
}

function scheme(id: string, name: string, s: S): TerminalScheme {
  return { id, name, ...s }
}

/** Built-in schemes, in gallery order. */
export const BUILTIN_SCHEMES: readonly TerminalScheme[] = Object.freeze([
  scheme('termstead-dark', 'Termstead Dark', {
    background: '#16181d',
    foreground: '#d4d8df',
    cursor: '#8cbcff',
    cursorAccent: '#16181d',
    selectionBackground: '#2f4a6e',
    black: '#2a2f38',
    red: '#f0717a',
    green: '#8fcf7a',
    yellow: '#e8c26e',
    blue: '#6aa7f5',
    magenta: '#c792ea',
    cyan: '#5ccfe0',
    white: '#c8ced8',
    brightBlack: '#5b6472',
    brightRed: '#ff8a92',
    brightGreen: '#a6e08f',
    brightYellow: '#f5d58a',
    brightBlue: '#8cbcff',
    brightMagenta: '#d7a8f5',
    brightCyan: '#7fe0ee',
    brightWhite: '#f2f4f8',
  }),
  scheme('termstead-light', 'Termstead Light', {
    background: '#ffffff',
    foreground: '#1f2430',
    cursor: '#1f5fd1',
    cursorAccent: '#ffffff',
    selectionBackground: '#bcd3f7',
    black: '#1f2430',
    red: '#c7253e',
    green: '#2f7d32',
    yellow: '#9a6a00',
    blue: '#1f5fd1',
    magenta: '#8a3fb8',
    cyan: '#0f7c8c',
    white: '#c9ced6',
    brightBlack: '#6b7280',
    brightRed: '#e0364f',
    brightGreen: '#3d9a41',
    brightYellow: '#b8860b',
    brightBlue: '#3b7cf0',
    brightMagenta: '#a653d6',
    brightCyan: '#1596a8',
    brightWhite: '#f3f4f6',
  }),
  scheme('classic', 'Classic (black)', {
    background: '#000000',
    foreground: '#ececec',
    cursor: '#ececec',
    cursorAccent: '#000000',
    selectionBackground: '#4a4a4a',
    black: '#000000',
    red: '#cd0000',
    green: '#00cd00',
    yellow: '#cdcd00',
    blue: '#1e90ff',
    magenta: '#cd00cd',
    cyan: '#00cdcd',
    white: '#e5e5e5',
    brightBlack: '#7f7f7f',
    brightRed: '#ff0000',
    brightGreen: '#00ff00',
    brightYellow: '#ffff00',
    brightBlue: '#4aa8ff',
    brightMagenta: '#ff00ff',
    brightCyan: '#00ffff',
    brightWhite: '#ffffff',
  }),
  scheme('tango-dark', 'Tango Dark', { background: '#2e3436', foreground: '#d3d7cf', cursor: '#d3d7cf', selectionBackground: '#555753', ...TANGO }),
  scheme('tango-light', 'Tango Light', { background: '#eeeeec', foreground: '#2e3436', cursor: '#2e3436', selectionBackground: '#c4c6c1', ...TANGO }),
  scheme('solarized-dark', 'Solarized Dark', {
    background: '#002b36',
    foreground: '#839496',
    cursor: '#93a1a1',
    cursorAccent: '#002b36',
    selectionBackground: '#073642',
    selectionForeground: '#93a1a1',
    ...SOLARIZED,
  }),
  scheme('solarized-light', 'Solarized Light', {
    background: '#fdf6e3',
    foreground: '#657b83',
    cursor: '#586e75',
    cursorAccent: '#fdf6e3',
    selectionBackground: '#eee8d5',
    selectionForeground: '#586e75',
    ...SOLARIZED,
  }),
  scheme('dracula', 'Dracula', {
    background: '#282a36',
    foreground: '#f8f8f2',
    cursor: '#f8f8f2',
    cursorAccent: '#282a36',
    selectionBackground: '#44475a',
    black: '#21222c',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
    blue: '#bd93f9',
    magenta: '#ff79c6',
    cyan: '#8be9fd',
    white: '#f8f8f2',
    brightBlack: '#6272a4',
    brightRed: '#ff6e6e',
    brightGreen: '#69ff94',
    brightYellow: '#ffffa5',
    brightBlue: '#d6acff',
    brightMagenta: '#ff92df',
    brightCyan: '#a4ffff',
    brightWhite: '#ffffff',
  }),
  scheme('one-dark', 'One Dark', {
    background: '#282c34',
    foreground: '#abb2bf',
    cursor: '#528bff',
    cursorAccent: '#282c34',
    selectionBackground: '#3e4451',
    black: '#3f4451',
    red: '#e06c75',
    green: '#98c379',
    yellow: '#e5c07b',
    blue: '#61afef',
    magenta: '#c678dd',
    cyan: '#56b6c2',
    white: '#d7dae0',
    brightBlack: '#5c6370',
    brightRed: '#be5046',
    brightGreen: '#98c379',
    brightYellow: '#d19a66',
    brightBlue: '#61afef',
    brightMagenta: '#c678dd',
    brightCyan: '#56b6c2',
    brightWhite: '#ffffff',
  }),
  scheme('monokai', 'Monokai', {
    background: '#272822',
    foreground: '#f8f8f2',
    cursor: '#f8f8f0',
    cursorAccent: '#272822',
    selectionBackground: '#49483e',
    black: '#272822',
    red: '#f92672',
    green: '#a6e22e',
    yellow: '#f4bf75',
    blue: '#66d9ef',
    magenta: '#ae81ff',
    cyan: '#a1efe4',
    white: '#f8f8f2',
    brightBlack: '#75715e',
    brightRed: '#f92672',
    brightGreen: '#a6e22e',
    brightYellow: '#f4bf75',
    brightBlue: '#66d9ef',
    brightMagenta: '#ae81ff',
    brightCyan: '#a1efe4',
    brightWhite: '#f9f8f5',
  }),
  scheme('nord', 'Nord', {
    background: '#2e3440',
    foreground: '#d8dee9',
    cursor: '#d8dee9',
    cursorAccent: '#2e3440',
    selectionBackground: '#434c5e',
    black: '#3b4252',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
    blue: '#81a1c1',
    magenta: '#b48ead',
    cyan: '#88c0d0',
    white: '#e5e9f0',
    brightBlack: '#4c566a',
    brightRed: '#bf616a',
    brightGreen: '#a3be8c',
    brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1',
    brightMagenta: '#b48ead',
    brightCyan: '#8fbcbb',
    brightWhite: '#eceff4',
  }),
  scheme('gruvbox-dark', 'Gruvbox Dark', {
    background: '#282828',
    foreground: '#ebdbb2',
    cursor: '#ebdbb2',
    cursorAccent: '#282828',
    selectionBackground: '#504945',
    black: '#282828',
    red: '#cc241d',
    green: '#98971a',
    yellow: '#d79921',
    blue: '#458588',
    magenta: '#b16286',
    cyan: '#689d6a',
    white: '#a89984',
    brightBlack: '#928374',
    brightRed: '#fb4934',
    brightGreen: '#b8bb26',
    brightYellow: '#fabd2f',
    brightBlue: '#83a598',
    brightMagenta: '#d3869b',
    brightCyan: '#8ec07c',
    brightWhite: '#ebdbb2',
  }),
  scheme('gruvbox-light', 'Gruvbox Light', {
    background: '#fbf1c7',
    foreground: '#3c3836',
    cursor: '#3c3836',
    cursorAccent: '#fbf1c7',
    selectionBackground: '#d5c4a1',
    black: '#fbf1c7',
    red: '#cc241d',
    green: '#98971a',
    yellow: '#d79921',
    blue: '#458588',
    magenta: '#b16286',
    cyan: '#689d6a',
    white: '#7c6f64',
    brightBlack: '#928374',
    brightRed: '#9d0006',
    brightGreen: '#79740e',
    brightYellow: '#b57614',
    brightBlue: '#076678',
    brightMagenta: '#8f3f71',
    brightCyan: '#427b58',
    brightWhite: '#3c3836',
  }),
  scheme('tokyo-night', 'Tokyo Night', {
    background: '#1a1b26',
    foreground: '#c0caf5',
    cursor: '#c0caf5',
    cursorAccent: '#1a1b26',
    selectionBackground: '#33467c',
    black: '#15161e',
    red: '#f7768e',
    green: '#9ece6a',
    yellow: '#e0af68',
    blue: '#7aa2f7',
    magenta: '#bb9af7',
    cyan: '#7dcfff',
    white: '#a9b1d6',
    brightBlack: '#414868',
    brightRed: '#f7768e',
    brightGreen: '#9ece6a',
    brightYellow: '#e0af68',
    brightBlue: '#7aa2f7',
    brightMagenta: '#bb9af7',
    brightCyan: '#7dcfff',
    brightWhite: '#c0caf5',
  }),
  scheme('catppuccin-mocha', 'Catppuccin Mocha', {
    background: '#1e1e2e',
    foreground: '#cdd6f4',
    cursor: '#f5e0dc',
    cursorAccent: '#1e1e2e',
    selectionBackground: '#585b70',
    black: '#45475a',
    red: '#f38ba8',
    green: '#a6e3a1',
    yellow: '#f9e2af',
    blue: '#89b4fa',
    magenta: '#f5c2e7',
    cyan: '#94e2d5',
    white: '#bac2de',
    brightBlack: '#585b70',
    brightRed: '#f38ba8',
    brightGreen: '#a6e3a1',
    brightYellow: '#f9e2af',
    brightBlue: '#89b4fa',
    brightMagenta: '#f5c2e7',
    brightCyan: '#94e2d5',
    brightWhite: '#a6adc8',
  }),
  scheme('catppuccin-latte', 'Catppuccin Latte', {
    background: '#eff1f5',
    foreground: '#4c4f69',
    cursor: '#dc8a78',
    cursorAccent: '#eff1f5',
    selectionBackground: '#acb0be',
    black: '#5c5f77',
    red: '#d20f39',
    green: '#40a02b',
    yellow: '#df8e1d',
    blue: '#1e66f5',
    magenta: '#ea76cb',
    cyan: '#179299',
    white: '#acb0be',
    brightBlack: '#6c6f85',
    brightRed: '#d20f39',
    brightGreen: '#40a02b',
    brightYellow: '#df8e1d',
    brightBlue: '#1e66f5',
    brightMagenta: '#ea76cb',
    brightCyan: '#179299',
    brightWhite: '#bcc0cc',
  }),
  scheme('github-dark', 'GitHub Dark', {
    background: '#0d1117',
    foreground: '#c9d1d9',
    cursor: '#58a6ff',
    cursorAccent: '#0d1117',
    selectionBackground: '#264f78',
    black: '#484f58',
    red: '#ff7b72',
    green: '#3fb950',
    yellow: '#d29922',
    blue: '#58a6ff',
    magenta: '#bc8cff',
    cyan: '#39c5cf',
    white: '#b1bac4',
    brightBlack: '#6e7681',
    brightRed: '#ffa198',
    brightGreen: '#56d364',
    brightYellow: '#e3b341',
    brightBlue: '#79c0ff',
    brightMagenta: '#d2a8ff',
    brightCyan: '#56d4dd',
    brightWhite: '#f0f6fc',
  }),
  scheme('github-light', 'GitHub Light', {
    background: '#ffffff',
    foreground: '#24292f',
    cursor: '#0969da',
    cursorAccent: '#ffffff',
    selectionBackground: '#b6d7ff',
    black: '#24292f',
    red: '#cf222e',
    green: '#116329',
    yellow: '#4d2d00',
    blue: '#0969da',
    magenta: '#8250df',
    cyan: '#1b7c83',
    white: '#6e7781',
    brightBlack: '#57606a',
    brightRed: '#a40e26',
    brightGreen: '#1a7f37',
    brightYellow: '#633c01',
    brightBlue: '#218bff',
    brightMagenta: '#a475f9',
    brightCyan: '#3192aa',
    brightWhite: '#8c959f',
  }),
  scheme('material', 'Material', {
    background: '#263238',
    foreground: '#eeffff',
    cursor: '#ffcc00',
    cursorAccent: '#263238',
    selectionBackground: '#37474f',
    black: '#000000',
    red: '#ff5370',
    green: '#c3e88d',
    yellow: '#ffcb6b',
    blue: '#82aaff',
    magenta: '#c792ea',
    cyan: '#89ddff',
    white: '#ffffff',
    brightBlack: '#546e7a',
    brightRed: '#ff5370',
    brightGreen: '#c3e88d',
    brightYellow: '#ffcb6b',
    brightBlue: '#82aaff',
    brightMagenta: '#c792ea',
    brightCyan: '#89ddff',
    brightWhite: '#ffffff',
  }),
  scheme('ayu-dark', 'Ayu Dark', {
    background: '#0b0e14',
    foreground: '#bfbdb6',
    cursor: '#e6b450',
    cursorAccent: '#0b0e14',
    selectionBackground: '#273747',
    black: '#01060e',
    red: '#ea6c73',
    green: '#91b362',
    yellow: '#f9af4f',
    blue: '#53bdfa',
    magenta: '#fae994',
    cyan: '#90e1c6',
    white: '#c7c7c7',
    brightBlack: '#686868',
    brightRed: '#f07178',
    brightGreen: '#c2d94c',
    brightYellow: '#ffb454',
    brightBlue: '#59c2ff',
    brightMagenta: '#ffee99',
    brightCyan: '#95e6cb',
    brightWhite: '#ffffff',
  }),
  scheme('ayu-light', 'Ayu Light', {
    background: '#fafafa',
    foreground: '#5c6166',
    cursor: '#ffaa33',
    cursorAccent: '#fafafa',
    selectionBackground: '#d1e4f4',
    black: '#000000',
    red: '#ea6c6d',
    green: '#6cbf43',
    yellow: '#eca944',
    blue: '#3199e1',
    magenta: '#9e75c7',
    cyan: '#46ba94',
    white: '#bababa',
    brightBlack: '#686868',
    brightRed: '#f07171',
    brightGreen: '#86b300',
    brightYellow: '#f2ae49',
    brightBlue: '#399ee6',
    brightMagenta: '#a37acc',
    brightCyan: '#4cbf99',
    brightWhite: '#d1d1d1',
  }),
  scheme('night-owl', 'Night Owl', {
    background: '#011627',
    foreground: '#d6deeb',
    cursor: '#7e57c2',
    cursorAccent: '#011627',
    selectionBackground: '#1d3b53',
    black: '#011627',
    red: '#ef5350',
    green: '#22da6e',
    yellow: '#addb67',
    blue: '#82aaff',
    magenta: '#c792ea',
    cyan: '#21c7a8',
    white: '#ffffff',
    brightBlack: '#575656',
    brightRed: '#ef5350',
    brightGreen: '#22da6e',
    brightYellow: '#ffeb95',
    brightBlue: '#82aaff',
    brightMagenta: '#c792ea',
    brightCyan: '#7fdbca',
    brightWhite: '#ffffff',
  }),
  scheme('everforest-dark', 'Everforest Dark', {
    background: '#2d353b',
    foreground: '#d3c6aa',
    cursor: '#d3c6aa',
    cursorAccent: '#2d353b',
    selectionBackground: '#475258',
    black: '#343f44',
    red: '#e67e80',
    green: '#a7c080',
    yellow: '#dbbc7f',
    blue: '#7fbbb3',
    magenta: '#d699b6',
    cyan: '#83c092',
    white: '#d3c6aa',
    brightBlack: '#7a8478',
    brightRed: '#e67e80',
    brightGreen: '#a7c080',
    brightYellow: '#dbbc7f',
    brightBlue: '#7fbbb3',
    brightMagenta: '#d699b6',
    brightCyan: '#83c092',
    brightWhite: '#e6dcc4',
  }),
  scheme('rose-pine', 'Rosé Pine', {
    background: '#191724',
    foreground: '#e0def4',
    cursor: '#e0def4',
    cursorAccent: '#191724',
    selectionBackground: '#403d52',
    black: '#26233a',
    red: '#eb6f92',
    green: '#31748f',
    yellow: '#f6c177',
    blue: '#9ccfd8',
    magenta: '#c4a7e7',
    cyan: '#ebbcba',
    white: '#e0def4',
    brightBlack: '#6e6a86',
    brightRed: '#eb6f92',
    brightGreen: '#31748f',
    brightYellow: '#f6c177',
    brightBlue: '#9ccfd8',
    brightMagenta: '#c4a7e7',
    brightCyan: '#ebbcba',
    brightWhite: '#e0def4',
  }),
  scheme('rose-pine-dawn', 'Rosé Pine Dawn', {
    background: '#faf4ed',
    foreground: '#575279',
    cursor: '#575279',
    cursorAccent: '#faf4ed',
    selectionBackground: '#dfdad9',
    black: '#f2e9e1',
    red: '#b4637a',
    green: '#286983',
    yellow: '#ea9d34',
    blue: '#56949f',
    magenta: '#907aa9',
    cyan: '#d7827e',
    white: '#575279',
    brightBlack: '#9893a5',
    brightRed: '#b4637a',
    brightGreen: '#286983',
    brightYellow: '#ea9d34',
    brightBlue: '#56949f',
    brightMagenta: '#907aa9',
    brightCyan: '#d7827e',
    brightWhite: '#575279',
  }),
  scheme('kanagawa', 'Kanagawa', {
    background: '#1f1f28',
    foreground: '#dcd7ba',
    cursor: '#c8c093',
    cursorAccent: '#1f1f28',
    selectionBackground: '#2d4f67',
    black: '#090618',
    red: '#c34043',
    green: '#76946a',
    yellow: '#c0a36e',
    blue: '#7e9cd8',
    magenta: '#957fb8',
    cyan: '#6a9589',
    white: '#c8c093',
    brightBlack: '#727169',
    brightRed: '#e82424',
    brightGreen: '#98bb6c',
    brightYellow: '#e6c384',
    brightBlue: '#7fb4ca',
    brightMagenta: '#938aa9',
    brightCyan: '#7aa89f',
    brightWhite: '#dcd7ba',
  }),
  scheme('snazzy', 'Snazzy', {
    background: '#282a36',
    foreground: '#eff0eb',
    cursor: '#97979b',
    cursorAccent: '#282a36',
    selectionBackground: '#3e404f',
    black: '#282a36',
    red: '#ff5c57',
    green: '#5af78e',
    yellow: '#f3f99d',
    blue: '#57c7ff',
    magenta: '#ff6ac1',
    cyan: '#9aedfe',
    white: '#f1f1f0',
    brightBlack: '#686868',
    brightRed: '#ff5c57',
    brightGreen: '#5af78e',
    brightYellow: '#f3f99d',
    brightBlue: '#57c7ff',
    brightMagenta: '#ff6ac1',
    brightCyan: '#9aedfe',
    brightWhite: '#eff0eb',
  }),
  scheme('tomorrow-night', 'Tomorrow Night', {
    background: '#1d1f21',
    foreground: '#c5c8c6',
    cursor: '#c5c8c6',
    cursorAccent: '#1d1f21',
    selectionBackground: '#373b41',
    black: '#1d1f21',
    red: '#cc6666',
    green: '#b5bd68',
    yellow: '#f0c674',
    blue: '#81a2be',
    magenta: '#b294bb',
    cyan: '#8abeb7',
    white: '#c5c8c6',
    brightBlack: '#969896',
    brightRed: '#cc6666',
    brightGreen: '#b5bd68',
    brightYellow: '#f0c674',
    brightBlue: '#81a2be',
    brightMagenta: '#b294bb',
    brightCyan: '#8abeb7',
    brightWhite: '#ffffff',
  }),
  scheme('zenburn', 'Zenburn', {
    background: '#3f3f3f',
    foreground: '#dcdccc',
    cursor: '#73635a',
    cursorAccent: '#3f3f3f',
    selectionBackground: '#21322f',
    black: '#4d4d4d',
    red: '#705050',
    green: '#60b48a',
    yellow: '#f0dfaf',
    blue: '#506070',
    magenta: '#dc8cc3',
    cyan: '#8cd0d3',
    white: '#dcdccc',
    brightBlack: '#709080',
    brightRed: '#dca3a3',
    brightGreen: '#c3bf9f',
    brightYellow: '#e0cf9f',
    brightBlue: '#94bff3',
    brightMagenta: '#ec93d3',
    brightCyan: '#93e0e3',
    brightWhite: '#ffffff',
  }),
  scheme('cobalt2', 'Cobalt2', {
    background: '#193549',
    foreground: '#ffffff',
    cursor: '#f0cc09',
    cursorAccent: '#193549',
    selectionBackground: '#185294',
    black: '#000000',
    red: '#ff0000',
    green: '#38de21',
    yellow: '#ffe50a',
    blue: '#1460d2',
    magenta: '#ff005d',
    cyan: '#00bbbb',
    white: '#bbbbbb',
    brightBlack: '#555555',
    brightRed: '#f40e17',
    brightGreen: '#3bd01d',
    brightYellow: '#edc809',
    brightBlue: '#5555ff',
    brightMagenta: '#ff55ff',
    brightCyan: '#6ae3fa',
    brightWhite: '#ffffff',
  }),
  scheme('homebrew', 'Homebrew', {
    background: '#000000',
    foreground: '#00ff00',
    cursor: '#23ff18',
    cursorAccent: '#000000',
    selectionBackground: '#083905',
    black: '#000000',
    red: '#990000',
    green: '#00a600',
    yellow: '#999900',
    blue: '#0000b2',
    magenta: '#b200b2',
    cyan: '#00a6b2',
    white: '#bfbfbf',
    brightBlack: '#666666',
    brightRed: '#e50000',
    brightGreen: '#00d900',
    brightYellow: '#e5e500',
    brightBlue: '#0000ff',
    brightMagenta: '#e500e5',
    brightCyan: '#00e5e5',
    brightWhite: '#e5e5e5',
  }),
  scheme('ubuntu', 'Ubuntu', { background: '#300a24', foreground: '#eeeeec', cursor: '#bbbbbb', cursorAccent: '#300a24', selectionBackground: '#5e2750', ...TANGO }),
  scheme('powershell', 'PowerShell', { background: '#012456', foreground: '#eeeeee', cursor: '#fedba9', cursorAccent: '#012456', selectionBackground: '#264f78', ...CAMPBELL }),
  scheme('campbell', 'Windows Terminal Campbell', { background: '#0c0c0c', foreground: '#cccccc', cursor: '#ffffff', cursorAccent: '#0c0c0c', selectionBackground: '#3a3a3a', ...CAMPBELL }),
  scheme('xterm', 'XTerm', {
    background: '#000000',
    foreground: '#e5e5e5',
    cursor: '#e5e5e5',
    cursorAccent: '#000000',
    selectionBackground: '#404040',
    black: '#000000',
    red: '#cd0000',
    green: '#00cd00',
    yellow: '#cdcd00',
    blue: '#0000ee',
    magenta: '#cd00cd',
    cyan: '#00cdcd',
    white: '#e5e5e5',
    brightBlack: '#7f7f7f',
    brightRed: '#ff0000',
    brightGreen: '#00ff00',
    brightYellow: '#ffff00',
    brightBlue: '#5c5cff',
    brightMagenta: '#ff00ff',
    brightCyan: '#00ffff',
    brightWhite: '#ffffff',
  }),
  scheme('putty', 'PuTTY', {
    background: '#000000',
    foreground: '#bbbbbb',
    cursor: '#00ff00',
    cursorAccent: '#000000',
    selectionBackground: '#3c3c3c',
    black: '#000000',
    red: '#bb0000',
    green: '#00bb00',
    yellow: '#bbbb00',
    blue: '#0000bb',
    magenta: '#bb00bb',
    cyan: '#00bbbb',
    white: '#bbbbbb',
    brightBlack: '#555555',
    brightRed: '#ff5555',
    brightGreen: '#55ff55',
    brightYellow: '#ffff55',
    brightBlue: '#5555ff',
    brightMagenta: '#ff55ff',
    brightCyan: '#55ffff',
    brightWhite: '#ffffff',
  }),
  scheme('linux-console', 'Linux Console', {
    background: '#000000',
    foreground: '#aaaaaa',
    cursor: '#aaaaaa',
    cursorAccent: '#000000',
    selectionBackground: '#555555',
    black: '#000000',
    red: '#aa0000',
    green: '#00aa00',
    yellow: '#aa5500',
    blue: '#0000aa',
    magenta: '#aa00aa',
    cyan: '#00aaaa',
    white: '#aaaaaa',
    brightBlack: '#555555',
    brightRed: '#ff5555',
    brightGreen: '#55ff55',
    brightYellow: '#ffff55',
    brightBlue: '#5555ff',
    brightMagenta: '#ff55ff',
    brightCyan: '#55ffff',
    brightWhite: '#ffffff',
  }),
])

export const CUSTOM_PREFIX = 'custom:'

const byId = new Map(BUILTIN_SCHEMES.map((s) => [s.id, s]))
/** Former ids of renamed built-in schemes, so saved settings keep resolving. */
const ALIASES: Record<string, string> = { mobaxterm: 'classic' }

/** All selectable schemes: built-ins followed by the user's custom schemes (ids prefixed with `custom:`). */
export function listSchemes(custom: readonly TerminalScheme[] = []): TerminalScheme[] {
  return [...BUILTIN_SCHEMES, ...custom.map((c) => ({ ...c, id: c.id.startsWith(CUSTOM_PREFIX) ? c.id : CUSTOM_PREFIX + c.id }))]
}

/** Look a scheme up by id (built-in or custom); falls back to Termstead Dark/Light. */
export function findScheme(id: string | undefined, custom: readonly TerminalScheme[] = [], fallbackDark = true): TerminalScheme {
  if (id) {
    const b = byId.get(ALIASES[id] ?? id)
    if (b) return b
    if (id.startsWith(CUSTOM_PREFIX)) {
      const raw = id.slice(CUSTOM_PREFIX.length)
      const c = custom.find((s) => s.id === raw || s.id === id)
      if (c) return normalizeScheme(c)
    }
  }
  return byId.get(fallbackDark ? 'termstead-dark' : 'termstead-light')!
}

/** Scheme for the current UI theme (TERM-9 auto light/dark switching). */
export function resolveScheme(s: Pick<TerminalSettings, 'theme' | 'lightTheme' | 'matchAppTheme' | 'customSchemes'>, uiDark: boolean): TerminalScheme {
  const id = s.matchAppTheme && !uiDark && s.lightTheme ? s.lightTheme : s.theme
  return findScheme(id, s.customSchemes, uiDark)
}

// ---------------------------------------------------------------------------------------------------------------------
// colour helpers
// ---------------------------------------------------------------------------------------------------------------------

const HEX6 = /^#[0-9a-f]{6}$/i
const HEX3 = /^#[0-9a-f]{3}$/i
const HEX8 = /^#[0-9a-f]{8}$/i

/** Normalise a colour string to #rrggbb (accepts #rgb, #rrggbbaa, rgb()/rgba()); returns undefined when unparsable. */
export function toHex(color: string | undefined | null): string | undefined {
  if (!color || typeof color !== 'string') return undefined
  const c = color.trim()
  if (HEX6.test(c)) return c.toLowerCase()
  if (HEX3.test(c)) return ('#' + c.slice(1).replace(/./g, (x) => x + x)).toLowerCase()
  if (HEX8.test(c)) return c.slice(0, 7).toLowerCase()
  const m = c.match(/^rgba?\(\s*(\d{1,3})[\s,]+(\d{1,3})[\s,]+(\d{1,3})/i)
  if (m) return rgbToHex(+m[1], +m[2], +m[3])
  return undefined
}

export function rgbToHex(r: number, g: number, b: number): string {
  const h = (v: number) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')
  return `#${h(r)}${h(g)}${h(b)}`
}

export function hexToRgb(hex: string): [number, number, number] {
  const h = toHex(hex) ?? '#000000'
  const n = parseInt(h.slice(1), 16)
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255]
}

/** Relative luminance (WCAG). */
export function luminance(hex: string): number {
  const [r, g, b] = hexToRgb(hex).map((v) => {
    const c = v / 255
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
  })
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}

export function isDarkScheme(s: Pick<TerminalScheme, 'background'>): boolean {
  return luminance(s.background) < 0.4
}

/** Mix two colours (t = 0 → a, 1 → b). */
export function mix(a: string, b: string, t: number): string {
  const [ar, ag, ab] = hexToRgb(a)
  const [br, bg, bb] = hexToRgb(b)
  return rgbToHex(ar + (br - ar) * t, ag + (bg - ag) * t, ab + (bb - ab) * t)
}

function withAlpha(hex: string, alpha: number): string {
  const [r, g, b] = hexToRgb(hex)
  return `rgba(${r}, ${g}, ${b}, ${Math.max(0, Math.min(1, alpha))})`
}

/** Fill in missing optional colours and normalise every value to #rrggbb. */
export function normalizeScheme(s: TerminalScheme): TerminalScheme {
  const bg = toHex(s.background) ?? '#000000'
  const fg = toHex(s.foreground) ?? '#ffffff'
  const out: TerminalScheme = {
    id: s.id,
    name: s.name || 'Untitled',
    background: bg,
    foreground: fg,
    cursor: toHex(s.cursor) ?? fg,
    cursorAccent: toHex(s.cursorAccent) ?? bg,
    selectionBackground: toHex(s.selectionBackground) ?? mix(bg, fg, 0.28),
    selectionForeground: toHex(s.selectionForeground),
  } as TerminalScheme
  const fallback = BUILTIN_SCHEMES[isDarkScheme({ background: bg }) ? 0 : 1]
  for (const k of ANSI_KEYS) out[k] = toHex(s[k]) ?? fallback[k]
  return out
}

/** xterm ITheme for a scheme; `opacity` < 1 makes the background translucent (requires allowTransparency). */
export function toXtermTheme(s: TerminalScheme, opacity = 1): ITheme {
  const n = normalizeScheme(s)
  const dark = isDarkScheme(n)
  const theme: ITheme = {
    background: opacity < 1 ? withAlpha(n.background, opacity) : n.background,
    foreground: n.foreground,
    cursor: n.cursor,
    cursorAccent: n.cursorAccent,
    selectionBackground: n.selectionBackground,
    selectionForeground: n.selectionForeground,
    selectionInactiveBackground: withAlpha(n.selectionBackground ?? mix(n.background, n.foreground, 0.28), 0.6),
    scrollbarSliderBackground: withAlpha(n.foreground, dark ? 0.18 : 0.22),
    scrollbarSliderHoverBackground: withAlpha(n.foreground, dark ? 0.32 : 0.36),
    scrollbarSliderActiveBackground: withAlpha(n.foreground, 0.45),
    overviewRulerBorder: n.background,
  }
  for (const k of ANSI_KEYS) theme[k] = n[k]
  return theme
}

/** Colours of search decorations derived from the scheme (xterm requires #rrggbb). */
export function searchColors(s: TerminalScheme) {
  const n = normalizeScheme(s)
  const dark = isDarkScheme(n)
  return {
    matchBackground: dark ? mix(n.background, '#d4a017', 0.35) : mix(n.background, '#f5c542', 0.55),
    matchBorder: dark ? '#8a7a2a' : '#c9a227',
    matchOverviewRuler: '#d4a017',
    activeMatchBackground: dark ? '#b8860b' : '#f59e0b',
    activeMatchBorder: dark ? '#ffd166' : '#b45309',
    activeMatchColorOverviewRuler: '#ff9f1c',
  }
}

/** Generate a unique id for a new custom scheme. */
export function newSchemeId(): string {
  const b = new Uint8Array(6)
  crypto.getRandomValues(b)
  return Array.from(b, (x) => x.toString(16).padStart(2, '0')).join('')
}
