/*
 * A compact, EFF-style word list for passphrase generation (CC-13): ~1950 short, unambiguous, common English words
 * (≈ 10.9 bits of entropy per word; the generator computes the exact figure from the list length). No word contains a
 * separator character, so passphrases split unambiguously.
 */
export const WORDLIST: readonly string[] = [
  'able', 'acid', 'acorn', 'acre', 'actor', 'adapt', 'admit', 'adopt', 'adult', 'agent', 'agree', 'ahead', 'aim', 'air',
  'aisle', 'alarm', 'album', 'alert', 'algae', 'alien', 'alike', 'alive', 'aloe', 'alpha', 'amber', 'amble', 'amend',
  'amid', 'ample', 'angel', 'anger', 'angle', 'ankle', 'apart', 'apple', 'apply', 'apron', 'arena', 'argue', 'arise',
  'armor', 'array', 'arrow', 'ashes', 'aside', 'asset', 'atlas', 'atom', 'attic', 'audio', 'audit', 'aunt', 'avoid',
  'awake', 'award', 'aware', 'awful', 'axis', 'bacon', 'badge', 'bagel', 'baker', 'balmy', 'banjo', 'barge', 'basil',
  'basin', 'basis', 'batch', 'baton', 'beach', 'beacon', 'beam', 'bean', 'bear', 'beast', 'beat', 'beaver', 'beef',
  'began', 'begin', 'being', 'belly', 'below', 'bench', 'bend', 'berry', 'best', 'beta', 'bike', 'bill', 'birch',
  'bird', 'birth', 'bison', 'black', 'blade', 'blank', 'blast', 'blaze', 'bleak', 'blend', 'bless', 'blimp', 'blink',
  'bliss', 'block', 'bloom', 'blue', 'blur', 'blush', 'board', 'boast', 'boat', 'bold', 'bolt', 'bond', 'bone', 'bonus',
  'book', 'boost', 'booth', 'boots', 'boss', 'both', 'bound', 'bowl', 'brace', 'braid', 'brain', 'brake', 'branch',
  'brand', 'brass', 'brave', 'bread', 'break', 'brew', 'brick', 'bride', 'brief', 'bring', 'brink', 'brisk', 'broad',
  'broil', 'broke', 'brook', 'broom', 'brown', 'brush', 'buddy', 'budge', 'buggy', 'build', 'bulb', 'bulk', 'bunch',
  'bunny', 'burst', 'cabin', 'cable', 'cache', 'cactus', 'cage', 'cake', 'calm', 'camel', 'camp', 'canal', 'candy',
  'cane', 'canoe', 'canon', 'canyon', 'cape', 'card', 'cargo', 'carol', 'carry', 'carve', 'case', 'cash', 'catch',
  'cause', 'cave', 'cedar', 'cello', 'chain', 'chair', 'chalk', 'champ', 'chant', 'chaos', 'charm', 'chart', 'chase',
  'cheek', 'cheer', 'chef', 'cherry', 'chess', 'chest', 'chew', 'chief', 'child', 'chili', 'chill', 'chime', 'chin',
  'chip', 'chirp', 'choir', 'chomp', 'chord', 'chose', 'chunk', 'churn', 'cider', 'cigar', 'cinch', 'circle', 'city',
  'civic', 'civil', 'claim', 'clamp', 'clang', 'clap', 'clash', 'clasp', 'class', 'claw', 'clay', 'clean', 'clear',
  'cleat', 'clerk', 'click', 'cliff', 'climb', 'cling', 'clip', 'cloak', 'clock', 'clone', 'close', 'cloth', 'cloud',
  'clove', 'clown', 'club', 'clue', 'clump', 'coach', 'coal', 'coast', 'coat', 'cobra', 'cocoa', 'code', 'coil',
  'coin', 'cola', 'cold', 'colt', 'comet', 'comic', 'coral', 'cord', 'core', 'cork', 'corn', 'couch', 'cough', 'count',
  'court', 'cover', 'cozy', 'crab', 'crack', 'craft', 'cramp', 'crane', 'crash', 'crate', 'crawl', 'crazy', 'cream',
  'creek', 'crepe', 'crest', 'crew', 'crib', 'crisp', 'croak', 'crop', 'cross', 'crowd', 'crown', 'crumb', 'crush',
  'crust', 'cube', 'cuff', 'curl', 'curry', 'curve', 'cycle', 'daily', 'dairy', 'daisy', 'dance', 'dandy', 'dark',
  'dart', 'dash', 'data', 'dawn', 'deal', 'dealt', 'debit', 'debug', 'decaf', 'decay', 'deck', 'decoy', 'deed', 'deep',
  'deer', 'delay', 'delta', 'demo', 'denim', 'dense', 'depth', 'derby', 'desk', 'dial', 'diary', 'dice', 'diet',
  'digit', 'dime', 'diner', 'dingo', 'diode', 'dirt', 'disco', 'dish', 'ditch', 'dive', 'dizzy', 'dock', 'dodge',
  'doing', 'dome', 'donor', 'donut', 'door', 'dose', 'dote', 'dough', 'dove', 'dowel', 'dozen', 'draft', 'drag',
  'drain', 'drama', 'drank', 'draw', 'dream', 'dress', 'dried', 'drift', 'drill', 'drink', 'drip', 'drive', 'drone',
  'drove', 'drum', 'dry', 'duck', 'duct', 'dude', 'duet', 'duke', 'dull', 'duly', 'dune', 'dusk', 'dust', 'duty',
  'eager', 'eagle', 'early', 'earn', 'earth', 'ease', 'east', 'easy', 'eaten', 'echo', 'eclair', 'edge', 'eel',
  'eject', 'elbow', 'elder', 'elf', 'elite', 'elk', 'elm', 'elope', 'ember', 'empty', 'ended', 'enemy', 'enjoy',
  'enter', 'entry', 'envy', 'epic', 'equal', 'error', 'erupt', 'essay', 'ether', 'evade', 'even', 'event', 'evict',
  'evoke', 'exact', 'exam', 'exile', 'exist', 'extra', 'fable', 'face', 'fact', 'fade', 'fail', 'faint', 'fair',
  'fairy', 'faith', 'fake', 'fall', 'false', 'fancy', 'fang', 'farm', 'fast', 'fate', 'fault', 'favor', 'fax', 'feast',
  'feed', 'feel', 'fell', 'femur', 'fence', 'fern', 'ferry', 'fetch', 'fever', 'fiber', 'field', 'fifth', 'fifty',
  'fig', 'fight', 'file', 'fill', 'film', 'final', 'finch', 'find', 'fine', 'fire', 'firm', 'first', 'fish', 'fist',
  'five', 'fix', 'flag', 'flair', 'flame', 'flank', 'flap', 'flare', 'flash', 'flask', 'flat', 'flaw', 'fled', 'flee',
  'flesh', 'flew', 'flick', 'flint', 'float', 'flock', 'flood', 'floor', 'flora', 'floss', 'flour', 'flow', 'fluff',
  'fluid', 'flute', 'foam', 'focal', 'focus', 'foggy', 'foil', 'fold', 'folk', 'font', 'food', 'fool', 'foot', 'force',
  'fork', 'form', 'fort', 'forty', 'found', 'four', 'fox', 'frame', 'frank', 'fresh', 'fried', 'frill', 'frog', 'front',
  'frost', 'frown', 'fruit', 'fuel', 'full', 'fume', 'fund', 'funny', 'furry', 'fuse', 'fuzzy', 'gadget', 'gain',
  'gala', 'game', 'gap', 'garden', 'gate', 'gauge', 'gave', 'gaze', 'gear', 'gecko', 'gem', 'genre', 'ghost', 'giant',
  'gift', 'gill', 'given', 'glad', 'glass', 'glaze', 'gleam', 'glide', 'globe', 'gloom', 'glory', 'gloss', 'glove',
  'glow', 'glue', 'goal', 'goat', 'gold', 'golf', 'gone', 'gong', 'good', 'goose', 'gore', 'gown', 'grab', 'grace',
  'grade', 'grain', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grave', 'gravy', 'gray', 'graze', 'great',
  'greed', 'green', 'greet', 'grew', 'grid', 'grief', 'grill', 'grim', 'grin', 'grip', 'grit', 'groom', 'group',
  'grove', 'grow', 'gruff', 'guard', 'guess', 'guest', 'guide', 'guild', 'gulf', 'gull', 'gulp', 'gust', 'habit',
  'hail', 'hair', 'half', 'hall', 'halt', 'hand', 'handy', 'hang', 'happy', 'harbor', 'hardy', 'harm', 'harp', 'harsh',
  'haste', 'hatch', 'haul', 'haven', 'hawk', 'hazel', 'heap', 'heard', 'heart', 'heat', 'heavy', 'hedge', 'heel',
  'hefty', 'help', 'herb', 'herd', 'hero', 'hill', 'hint', 'hive', 'hobby', 'hold', 'hole', 'honey', 'hood', 'hoof',
  'hook', 'hope', 'horn', 'horse', 'hose', 'host', 'hotel', 'hound', 'hour', 'house', 'hover', 'howl', 'hub', 'huge',
  'hull', 'human', 'humid', 'humor', 'hunt', 'hurl', 'hurry', 'hush', 'hutch', 'hydra', 'ice', 'icing', 'icon', 'idea',
  'igloo', 'image', 'inbox', 'inch', 'index', 'inept', 'ingot', 'inlet', 'input', 'ionic', 'iris', 'iron', 'irony',
  'islet', 'issue', 'ivory', 'jacket', 'jade', 'jam', 'jar', 'jaunt', 'jaw', 'jazz', 'jeans', 'jelly', 'jet', 'jewel',
  'jiffy', 'jog', 'joint', 'joke', 'jolly', 'jolt', 'joust', 'judge', 'juice', 'juicy', 'jumbo', 'jump', 'junk',
  'kale', 'karma', 'kayak', 'keel', 'keen', 'keep', 'kelp', 'kept', 'kettle', 'key', 'khaki', 'kick', 'kilt', 'kind',
  'king', 'kiosk', 'kit', 'kite', 'kitten', 'kiwi', 'knack', 'knee', 'knelt', 'knife', 'knob', 'knock', 'knot', 'know',
  'koala', 'label', 'labor', 'lace', 'lack', 'ladle', 'lady', 'lake', 'lamb', 'lamp', 'lance', 'land', 'lane', 'lard',
  'large', 'lark', 'laser', 'lasso', 'last', 'latch', 'later', 'latex', 'lathe', 'laugh', 'lava', 'lawn', 'layer',
  'lazy', 'leaf', 'leak', 'lean', 'leap', 'learn', 'lease', 'leash', 'least', 'leave', 'ledge', 'leek', 'left', 'lemon',
  'lend', 'lens', 'lentil', 'level', 'lever', 'light', 'like', 'lilac', 'lily', 'limb', 'lime', 'limit', 'line',
  'linen', 'link', 'lion', 'list', 'liver', 'llama', 'load', 'loaf', 'loan', 'lobby', 'local', 'lock', 'lodge', 'loft',
  'logic', 'login', 'logo', 'lone', 'long', 'look', 'loop', 'loose', 'lord', 'lore', 'loss', 'lotus', 'loud', 'lounge',
  'love', 'lower', 'loyal', 'lucid', 'luck', 'lucky', 'lull', 'lump', 'lunar', 'lunch', 'lung', 'lush', 'lute', 'lynx',
  'macro', 'made', 'magic', 'magma', 'maid', 'mail', 'main', 'major', 'maker', 'mango', 'manor', 'many', 'maple',
  'march', 'mare', 'marsh', 'mask', 'mason', 'mass', 'mast', 'match', 'mate', 'math', 'matte', 'mauve', 'maze', 'meal',
  'mean', 'meat', 'medal', 'media', 'melon', 'melt', 'menu', 'meow', 'merge', 'merit', 'merry', 'mesa', 'mesh', 'metal',
  'meter', 'metro', 'micro', 'midst', 'might', 'milk', 'mill', 'mimic', 'mince', 'mind', 'mine', 'mini', 'mint',
  'minus', 'mist', 'mixer', 'moat', 'model', 'modem', 'moist', 'mold', 'mole', 'money', 'monk', 'month', 'mood', 'moon',
  'moose', 'moral', 'morph', 'moss', 'moth', 'motor', 'motto', 'mound', 'mount', 'mouse', 'mouth', 'move', 'movie',
  'much', 'mucus', 'muddy', 'muffin', 'mug', 'mule', 'multi', 'mummy', 'munch', 'mural', 'muse', 'music', 'musk',
  'must', 'mute', 'nacho', 'nail', 'name', 'nanny', 'nasal', 'navy', 'near', 'neat', 'neck', 'need', 'neon', 'nerve',
  'nest', 'never', 'newt', 'next', 'nice', 'niche', 'niece', 'night', 'nimble', 'ninja', 'ninth', 'noble', 'node',
  'noise', 'nomad', 'noon', 'north', 'nose', 'note', 'notch', 'novel', 'nudge', 'null', 'numb', 'nurse', 'nutmeg',
  'oak', 'oasis', 'oat', 'ocean', 'octet', 'offer', 'often', 'ogre', 'oil', 'okay', 'olive', 'omega', 'onion', 'only',
  'onto', 'onyx', 'open', 'opera', 'opt', 'orange', 'orbit', 'order', 'organ', 'otter', 'ounce', 'outer', 'oval',
  'oven', 'owl', 'own', 'oxen', 'ozone', 'pace', 'pack', 'pad', 'paddle', 'page', 'pail', 'pain', 'paint', 'pair',
  'palm', 'panda', 'panel', 'panic', 'pansy', 'pants', 'paper', 'park', 'parka', 'parry', 'part', 'party', 'pasta',
  'paste', 'patch', 'path', 'patio', 'pause', 'pave', 'pawn', 'peace', 'peach', 'peak', 'pearl', 'pecan', 'pedal',
  'peer', 'pelt', 'penny', 'peony', 'perch', 'perk', 'pest', 'petal', 'phase', 'phone', 'photo', 'piano', 'pick',
  'picky', 'piece', 'pier', 'piggy', 'pilot', 'pinch', 'pine', 'pink', 'pint', 'pipe', 'pitch', 'pivot', 'pixel',
  'pizza', 'place', 'plaid', 'plain', 'plan', 'plane', 'plank', 'plant', 'plate', 'play', 'plaza', 'plead', 'pleat',
  'plot', 'plow', 'pluck', 'plug', 'plum', 'plump', 'plus', 'poach', 'point', 'poise', 'poker', 'polar', 'pole',
  'polka', 'pond', 'pony', 'pool', 'porch', 'pore', 'port', 'pose', 'posh', 'post', 'pouch', 'pound', 'pour', 'power',
  'prank', 'press', 'price', 'pride', 'prime', 'print', 'prior', 'prism', 'prize', 'probe', 'prom', 'proof', 'props',
  'proud', 'prove', 'proxy', 'prune', 'pull', 'pulp', 'pulse', 'puma', 'pump', 'punch', 'pupil', 'puppy', 'purr',
  'purse', 'push', 'putty', 'quack', 'quail', 'quake', 'quart', 'query', 'quest', 'queue', 'quick', 'quiet', 'quill',
  'quilt', 'quirk', 'quota', 'quote', 'rabbit', 'race', 'rack', 'radar', 'radio', 'raft', 'rage', 'rail', 'rain',
  'raise', 'rake', 'rally', 'ramp', 'ranch', 'range', 'rank', 'rapid', 'rare', 'rash', 'raven', 'razor', 'reach',
  'react', 'read', 'realm', 'reap', 'rebel', 'recap', 'reef', 'reel', 'relax', 'relay', 'relic', 'remit', 'renew',
  'rent', 'repay', 'reply', 'reset', 'resin', 'rest', 'retro', 'rhino', 'rhyme', 'rice', 'rich', 'ride', 'ridge',
  'rifle', 'rigid', 'rind', 'ring', 'rinse', 'riot', 'ripe', 'rise', 'risk', 'ritual', 'river', 'roast', 'robe',
  'robin', 'robot', 'rock', 'rocky', 'rodeo', 'rogue', 'role', 'roll', 'roof', 'rook', 'room', 'roost', 'root', 'rope',
  'rose', 'rosy', 'rotor', 'rough', 'round', 'route', 'rover', 'royal', 'ruby', 'rug', 'rule', 'rumor', 'run', 'rune',
  'rung', 'runt', 'rural', 'rush', 'rust', 'sable', 'sad', 'safe', 'saga', 'sage', 'said', 'sail', 'saint', 'salad',
  'salon', 'salsa', 'salt', 'same', 'sand', 'sane', 'sappy', 'sash', 'sauce', 'saucy', 'sauna', 'save', 'savor',
  'scale', 'scan', 'scarf', 'scary', 'scene', 'scent', 'scoff', 'scone', 'scoop', 'scope', 'score', 'scorn', 'scout',
  'scrap', 'scrub', 'scuba', 'seal', 'seat', 'sedan', 'seed', 'self', 'sell', 'send', 'sense', 'serve', 'setup',
  'seven', 'sew', 'shack', 'shade', 'shady', 'shaft', 'shake', 'shaky', 'shale', 'shame', 'shape', 'share', 'shark',
  'sharp', 'shave', 'shawl', 'shed', 'sheep', 'sheet', 'shelf', 'shell', 'shine', 'shiny', 'ship', 'shirt', 'shock',
  'shoe', 'shone', 'shook', 'shoot', 'shop', 'shore', 'short', 'shout', 'shove', 'shown', 'showy', 'shred', 'shrub',
  'shrug', 'shush', 'shut', 'shy', 'sick', 'side', 'siege', 'sift', 'sigh', 'sight', 'sigma', 'silk', 'silky', 'silly',
  'silo', 'since', 'sinew', 'sing', 'siren', 'site', 'sixth', 'sixty', 'size', 'skate', 'sketch', 'ski', 'skid',
  'skiff', 'skill', 'skin', 'skip', 'skirt', 'skull', 'skunk', 'sky', 'slab', 'slam', 'slang', 'slant', 'slap',
  'slash', 'slate', 'sleek', 'sleep', 'sleet', 'slice', 'slick', 'slide', 'slim', 'slime', 'sling', 'slip', 'slope',
  'slot', 'sloth', 'slow', 'slug', 'slump', 'slurp', 'small', 'smart', 'smash', 'smell', 'smile', 'smirk', 'smog',
  'smoke', 'snack', 'snag', 'snail', 'snake', 'snap', 'snare', 'sneak', 'sniff', 'snoop', 'snore', 'snort', 'snout',
  'snow', 'snowy', 'snug', 'soak', 'soap', 'sober', 'sock', 'soda', 'sofa', 'soft', 'soggy', 'soil', 'solar', 'sole',
  'solid', 'solo', 'solve', 'sonar', 'song', 'sonic', 'soot', 'sort', 'soul', 'sound', 'soup', 'sour', 'south', 'space',
  'spade', 'spare', 'spark', 'speak', 'spear', 'speck', 'speed', 'spell', 'spend', 'spice', 'spicy', 'spike', 'spill',
  'spin', 'spine', 'spiny', 'spire', 'spite', 'splat', 'split', 'spoil', 'spoke', 'spoon', 'sport', 'spot', 'spout',
  'spray', 'spree', 'spring', 'sprint', 'sprout', 'spruce', 'spry', 'spur', 'spurt', 'squad', 'square', 'squid',
  'stack', 'staff', 'stage', 'stain', 'stair', 'stake', 'stale', 'stalk', 'stall', 'stamp', 'stand', 'staple', 'star',
  'stare', 'stark', 'start', 'stash', 'state', 'stay', 'steak', 'steam', 'steed', 'steel', 'steep', 'steer', 'stem',
  'step', 'stern', 'stew', 'stick', 'stiff', 'still', 'sting', 'stir', 'stock', 'stole', 'stomp', 'stone', 'stony',
  'stood', 'stool', 'stoop', 'stop', 'store', 'stork', 'storm', 'story', 'stout', 'stove', 'strap', 'straw', 'stray',
  'strip', 'strut', 'stub', 'stud', 'study', 'stuff', 'stump', 'stun', 'stunt', 'style', 'sugar', 'suit', 'sulky',
  'summer', 'sun', 'sunny', 'super', 'surf', 'surge', 'swab', 'swamp', 'swan', 'swap', 'swarm', 'sway', 'swear',
  'sweat', 'sweep', 'sweet', 'swell', 'swift', 'swim', 'swing', 'swirl', 'swish', 'swoop', 'sword', 'syrup', 'table',
  'tacit', 'tack', 'taco', 'tag', 'tail', 'take', 'tale', 'talk', 'tall', 'tally', 'tame', 'tango', 'tank', 'tape',
  'taper', 'tapir', 'tardy', 'task', 'taste', 'tasty', 'taunt', 'taut', 'teach', 'teal', 'team', 'tear', 'tease',
  'teddy', 'tempo', 'tempt', 'tend', 'tenor', 'tense', 'tent', 'tenth', 'tepid', 'term', 'test', 'text', 'thank',
  'thaw', 'theft', 'theme', 'thick', 'thigh', 'thin', 'thing', 'think', 'third', 'thorn', 'those', 'three', 'threw',
  'throb', 'throw', 'thumb', 'thump', 'tick', 'tidal', 'tide', 'tidy', 'tiger', 'tight', 'tile', 'till', 'tilt',
  'timer', 'tin', 'tiny', 'tip', 'tire', 'title', 'toad', 'toast', 'today', 'toe', 'tofu', 'toga', 'token', 'tomb',
  'tonal', 'tone', 'tong', 'tonic', 'took', 'tool', 'tooth', 'top', 'topaz', 'topic', 'torch', 'torso', 'toss',
  'total', 'tote', 'touch', 'tough', 'tour', 'towel', 'tower', 'town', 'toxic', 'trace', 'track', 'tract', 'trade',
  'trail', 'train', 'trait', 'tram', 'trap', 'trash', 'tray', 'tread', 'treat', 'tree', 'trek', 'trend', 'trial',
  'tribe', 'trick', 'tried', 'trill', 'trim', 'trio', 'trip', 'troll', 'troop', 'trout', 'truce', 'truck', 'true',
  'truly', 'trunk', 'trust', 'truth', 'try', 'tuba', 'tube', 'tuck', 'tug', 'tulip', 'tuna', 'tune', 'tunic', 'turf',
  'turn', 'tusk', 'tutor', 'tweak', 'tweet', 'twice', 'twig', 'twin', 'twine', 'twirl', 'twist', 'two', 'typo', 'udder',
  'ultra', 'uncle', 'under', 'undo', 'unify', 'union', 'unit', 'unite', 'unlit', 'until', 'unwed', 'unzip', 'upon',
  'upper', 'upset', 'urban', 'urge', 'usage', 'used', 'user', 'usher', 'usual', 'vague', 'valet', 'valid', 'value',
  'valve', 'van', 'vapor', 'vase', 'vast', 'vault', 'veer', 'vegan', 'veil', 'vein', 'velvet', 'vend', 'venom', 'vent',
  'venue', 'verb', 'verge', 'verse', 'very', 'vest', 'veto', 'vibe', 'video', 'view', 'vigor', 'villa', 'vine',
  'vinyl', 'viola', 'viper', 'viral', 'virus', 'visa', 'visit', 'visor', 'vista', 'vital', 'vivid', 'vocal', 'vogue',
  'voice', 'void', 'volt', 'vote', 'vowel', 'wafer', 'wag', 'wage', 'wagon', 'wail', 'waist', 'wait', 'wake', 'walk',
  'wall', 'walnut', 'wand', 'want', 'ward', 'ware', 'warm', 'warn', 'warp', 'wart', 'wash', 'wasp', 'watch', 'water',
  'watt', 'wave', 'wavy', 'wax', 'weak', 'wealth', 'weary', 'weave', 'wedge', 'weed', 'week', 'weep', 'weigh', 'weird',
  'weld', 'well', 'welt', 'west', 'whale', 'wharf', 'wheat', 'wheel', 'whelp', 'whiff', 'while', 'whim', 'whine',
  'whip', 'whirl', 'whisk', 'white', 'whole', 'whoop', 'wick', 'wide', 'widen', 'width', 'wield', 'wifi', 'wild',
  'will', 'wilt', 'wince', 'winch', 'wind', 'windy', 'wine', 'wing', 'wink', 'wipe', 'wire', 'wiry', 'wise', 'wish',
  'wisp', 'witch', 'with', 'witty', 'woke', 'wolf', 'woman', 'wombat', 'wonder', 'wood', 'woody', 'wool', 'woozy',
  'word', 'work', 'world', 'worm', 'worry', 'worse', 'worst', 'worth', 'wound', 'woven', 'wrap', 'wrath', 'wreath',
  'wreck', 'wren', 'wrist', 'write', 'wrong', 'yacht', 'yam', 'yard', 'yarn', 'yawn', 'year', 'yeast', 'yell', 'yield',
  'yodel', 'yoga', 'yolk', 'young', 'zebra', 'zero', 'zest', 'zesty', 'zigzag', 'zinc', 'zone', 'zoom',
]
