package anontls

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"math/big"
	"sync"
)

// Finite-field Diffie-Hellman parameter validation (RFC 5246 section 8.1.2, RFC 7919 section 5.1).
//
// Anonymous key exchange offers no protection against an active attacker, who simply runs its own key exchange with
// both sides; no amount of group validation changes that. Validation protects the case these suites are meant for:
// a passive eavesdropper on the connection to a weakly configured server. Rejected are moduli below MinDHBits
// (default 2048 bits, OpenSSL's security level 2: Logjam-style precomputation puts 1024-bit groups within reach),
// composite moduli (the discrete logarithm then splits into the logarithms modulo the factors, cf. the non-prime
// socat group of 2016), degenerate generators and public values in the trivial subgroups {1} and {1, p-1}.
//
// The standard groups (RFC 7919 FFDHE, RFC 3526 MODP; see groups.go) are safe primes and are recognized without a
// primality test; their only small subgroups are the trivial ones, so a 512-bit private exponent keeps the full
// strength (RFC 7919 section 5.2 asks for 225 to 400 bits). Any other modulus must pass a Baillie-PSW test (results
// are cached per modulus: the test of an unknown 8192-bit group takes seconds) and gets a full-length exponent,
// because an unknown group may have small factors in p-1 that short exponents would expose to Pohlig-Hellman /
// van Oorschot-Wiener attacks. Checking the order of the server's public value would need the subgroup order q,
// which the protocol does not carry for non-standard groups (DSA-style groups generated by GnuTLS are legitimate).

const (
	defaultMinDHBits  = 2048
	maxDHBits         = 8192
	knownGroupExpBits = 512
	primeCacheSize    = 64
)

// WeakGroupError reports a server Diffie-Hellman group below Config.MinDHBits (wrapped in the handshake error; the
// caller may offer the user to retry with a lower minimum).
type WeakGroupError struct {
	Bits, MinBits int
}

func (e *WeakGroupError) Error() string {
	return fmt.Sprintf("the server's Diffie-Hellman group is too small (%d bits, at least %d required)", e.Bits, e.MinBits)
}

var (
	knownGroupsOnce sync.Once
	knownGroups     map[string]string // modulus (minimal big-endian bytes) → name
)

func knownGroupName(p *big.Int) (string, bool) {
	knownGroupsOnce.Do(func() {
		knownGroups = make(map[string]string, len(knownGroupTable))
		for _, g := range knownGroupTable {
			b, err := hex.DecodeString(g.hex)
			if err != nil {
				panic("anontls: malformed group table entry " + g.name)
			}
			knownGroups[string(new(big.Int).SetBytes(b).Bytes())] = g.name
		}
	})
	name, ok := knownGroups[string(p.Bytes())]
	return name, ok
}

// primeCache remembers primality results of non-standard moduli (servers reuse their group on every connection).
var primeCache = struct {
	sync.Mutex
	m map[[32]byte]bool
}{m: map[[32]byte]bool{}}

func probablyPrime(p *big.Int) bool {
	key := sha256.Sum256(p.Bytes())
	primeCache.Lock()
	v, ok := primeCache.m[key]
	primeCache.Unlock()
	if ok {
		return v
	}
	// Baillie-PSW: no pseudoprime is known. It is not meant to resist moduli crafted to fool it, but whoever crafts
	// the group is the peer of this unauthenticated exchange and learns the shared secret anyway.
	v = p.ProbablyPrime(0)
	primeCache.Lock()
	if len(primeCache.m) >= primeCacheSize {
		for k := range primeCache.m {
			delete(primeCache.m, k)
			break
		}
	}
	primeCache.m[key] = v
	primeCache.Unlock()
	return v
}

// dhGroup is a validated server group.
type dhGroup struct {
	p, g  *big.Int
	name  string // "ffdhe2048", "modp2048", or "DH-<bits>" for other groups
	known bool
}

// parseDHGroup validates the server's DH parameters and public value (from ServerKeyExchange).
func parseDHGroup(pBytes, gBytes, ysBytes []byte, minBits int) (*dhGroup, *big.Int, error) {
	p := new(big.Int).SetBytes(pBytes)
	g := new(big.Int).SetBytes(gBytes)
	ys := new(big.Int).SetBytes(ysBytes)
	bits := p.BitLen()
	if bits < minBits {
		return nil, nil, &localAlert{desc: alertInsufficientSec, err: &WeakGroupError{Bits: bits, MinBits: minBits}}
	}
	if bits > maxDHBits {
		return nil, nil, fail(alertIllegalParameter, "the server's Diffie-Hellman group is too large (%d bits)", bits)
	}
	one := big.NewInt(1)
	pm1 := new(big.Int).Sub(p, one)
	if p.Bit(0) == 0 {
		return nil, nil, fail(alertInsufficientSec, "the server's Diffie-Hellman modulus is not prime")
	}
	if g.Cmp(one) <= 0 || g.Cmp(pm1) >= 0 {
		return nil, nil, fail(alertIllegalParameter, "invalid Diffie-Hellman generator")
	}
	if ys.Cmp(one) <= 0 || ys.Cmp(pm1) >= 0 {
		return nil, nil, fail(alertIllegalParameter, "invalid Diffie-Hellman public value")
	}
	name, known := knownGroupName(p)
	if !known {
		if !probablyPrime(p) {
			return nil, nil, fail(alertInsufficientSec, "the server's Diffie-Hellman modulus is not prime")
		}
		name = fmt.Sprintf("DH-%d", bits)
	}
	return &dhGroup{p: p, g: g, name: name, known: known}, ys, nil
}

// exchange generates the client key pair and computes the shared secret Z. yc is padded to the modulus length (as
// OpenSSL does); z has leading zero bytes stripped (RFC 5246 section 8.1.2). The caller wipes z.
func (d *dhGroup) exchange(rnd io.Reader, ys *big.Int) (yc, z []byte, err error) {
	two := big.NewInt(2)
	var x *big.Int
	if d.known {
		x, err = rand.Int(rnd, new(big.Int).Lsh(big.NewInt(1), knownGroupExpBits))
	} else {
		x, err = rand.Int(rnd, new(big.Int).Sub(d.p, big.NewInt(3))) // [0, p-4] → [2, p-2] below
	}
	if err != nil {
		return nil, nil, err
	}
	x.Add(x, two)
	defer wipe(x)
	ycInt := new(big.Int).Exp(d.g, x, d.p)
	zInt := new(big.Int).Exp(ys, x, d.p)
	defer wipe(zInt)
	if zInt.Cmp(big.NewInt(1)) <= 0 || zInt.Cmp(new(big.Int).Sub(d.p, big.NewInt(1))) >= 0 {
		return nil, nil, fail(alertIllegalParameter, "degenerate Diffie-Hellman shared secret")
	}
	return leftPad(ycInt.Bytes(), (d.p.BitLen()+7)/8), zInt.Bytes(), nil
}

// wipe overwrites the magnitude of secret integers (best effort: math/big may have left copies in temporaries).
func wipe(xs ...*big.Int) {
	for _, x := range xs {
		if x != nil {
			clear(x.Bits())
		}
	}
}

func leftPad(b []byte, n int) []byte {
	if len(b) >= n {
		return b
	}
	out := make([]byte, n)
	copy(out[n-len(b):], b)
	return out
}
